### ISSUE TITLE
Initial Spinup Tazks

### ISSUE THREAD

**Issue by pirog** [thinktandem/template-drupal8#1]
Let's keep this simple and stupid for now until we have this start state integrated into our forthcoming engineering process eg it has a budget.

### Porting old files

We need to move a bunch of shit from 
https://github.com/thinktandem/deprecated-platformsh-example-drupal8

- [x] Landofiles
- [x] Travisfiles
- [x] Codeclimate files
- [x] Lando settings.php file
- [x] Lets get some github PR/issue templates rolling (you can look at Lando as a starting point)

### README

- [x] We want to move our README from https://github.com/thinktandem/deprecated-platformsh-example-drupal8 but we also do not want to lose the upstream one. 

Is there a clever way to take advantage of 

> If you put your README file in your repository's root, docs, or hidden .github directory, GitHub will recognize and automatically surface your README to repository visitors.

from https://help.github.com/articles/about-readmes/ to have BOTH readmes in our repo but with our showing as project default?

### Using new Landofiles

- [x] In the newest version of Lando you can set a "base" file that can then be overridden by the usual `.lando.yml` 
https://docs.devwithlando.io/config/lando.html#base-file

We should probably do that there, and might be able to use this for our Travis landofile as well.
- [x] See if we can use .lando.base.yml to replace .travis.lando.yml

### Spin up some botz

We should add config for various bots so we can get all the automation out of the box. Check out https://github.com/lando/lando/tree/master/.github for a few but we should include config for the following:

- [x] https://probot.github.io/apps/stale/
- [x] https://probot.github.io/apps/delete-merged-branch/
- [x] https://probot.github.io/apps/ci-reporter/

### DevOps

- [x] Get a platform.sh site
- [x] Get Travis things running 

**Get Testing Working / Config Testing in Travis**
- [x] PHP Lint
- [x] PHP Codesniff
- [x] PHP Unit
- [x] [Drupal 9 Deprecation](https://glamanate.com/blog/testing-your-drupal-code-base-deprecated-code-usage-phpstan)

### Future things

- [ ] Some sort of "bootup" script so a user can git clone the start state and then spin up all the needed devops eg platform/github/travis/circle/codeclime etc (Optional for now)
- [ ] Some way to automatically submit pull requests when upstream updates are available, fork the "Pull Bot"

**Comment by labboy0276** [comment]
Another thing we need to consider @pirog is that our travis files are completely different and that could cause problems

**Comment by pirog** [comment]
Completely different? What’s different about them?

**Comment by labboy0276** [comment]
Theirs doesnt use any lando and there is more steps as they do things more natively + use simplytest me: https://github.com/platformsh/template-drupal8/blob/master/.travis.yml

As compared to ours: https://github.com/thinktandem/template-drupal8/blob/master/.travis.yml

@pirog

**Comment by pirog** [comment]
@labboy0276 ahhh right, sorry, i thought you were talking about the start state's travis yaml and then downstream ones eg minimis and projects. Those should be more or less the same.

I'm not really sure how to handle these situations but i think the best thing we can do for now is just rename their file to `.travis.platform.sh` and then spin up ours next to it. You have a better idea?

**Comment by labboy0276** [comment]
OK, there isnt much we can do and we will just have to manually adjust things at times @pirog

**Comment by labboy0276** [comment]
I used our project github templating for now as well

**Comment by labboy0276** [comment]
@pirog most things are done, can you spin up a platform instance for this?

**Comment by labboy0276** [comment]
travis is failing hard, need to stare more later on

**Comment by labboy0276** [comment]
We have to use a separate lando for travis because lando will get spit out warnings over the fact these vars are not set during build and start: 

```
        PLATFORMSH_CLI_TOKEN: "$PLATFORMSH_CLI_TOKEN"
        PLATFORMSH_PROJECT_ID: "$PLATFORMSH_PROJECT_ID"
```

**Comment by pirog** [comment]
its safe to hardcode the project ID, its also fine to have a warning as
long as its not breaking anything

**Comment by labboy0276** [comment]
OK, it has been banished then

**Comment by labboy0276** [comment]
@pirog I noticed I have php codesniffer in travis & codeclimate. Should I leave it like that or remove one from one of the testing (I suggest taking it out of travis) ?

**Comment by pirog** [comment]
i think its good to have it both because we arent super clear on whether we want to use codeclimate everywhere yet

**Comment by labboy0276** [comment]
@pirog as discussed this is good to go, any future tasks can be split off into their own cards

**Comment by pirog** [comment]
lets just roll fast and hard with our QA since our minds are one
